name: PR Update

# Update permissions to include all necessary ones
permissions:
  contents: read
  pull-requests: read
  actions: read
  checks: write
  id-token: write

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  required:
    name: PR Check Summary
    needs: [lint, build]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      statuses: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0
        with:
          egress-policy: audit
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1