name: Build, release & deploy Kopexa Docs images

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  docker-build:
    name: Build & release docker image
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/release-docker-github.yml
    secrets: inherit
    with:
      IS_PRERELEASE: ${{ github.event.release.prerelease }}

  devops-release:
    name: Push Tag to DevOps
    uses: ./.github/workflows/release-cd.yml
    secrets: inherit
    needs:
      - docker-build
    with:
      VERSION: ${{ needs.docker-build.outputs.VERSION }}